language: go
go_import_path: github.com/rockstardevs/goofx
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip
sudo: false
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - go test -v -race -covermode=atomic -coverprofile=profile.cov
after_success:
  - go get -v github.com/mattn/goveralls
  - goveralls -coverprofile=profile.cov -service=travis-ci
